language: python

python:
  - "3.2"
  - "3.3"

env:
#  - LLVM_VERSION=3.4
  - LLVM_VERSION=3.3
  - LLVM_VERSION=3.2
#  - LLVM_VERSION=3.1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq llvm-$LLVM_VERSION

install:
  - pip install coveralls
  - git clone git://github.com/llvmpy/llvmpy.git
  - cd llvmpy
  - LLVM_CONFIG_PATH=/usr/bin/llvm-config-$LLVM_VERSION python setup.py install
  - cd ..

script:
  - nosetests --with-coverage --cover-package=ctree --cover-min-percentage=90

after_success:
  coveralls
