language: python

python:
  - "3.2"
  - "3.3"

env:
  global:
    # encrypted OAuth token so Travis can commit docs back to Github
    - secure: "exjwYI5XtSjquJirXb1QuruUfT0W/q1E6XUEIoyVSs2+JFouU6PIVMUglckBlaC29t4riq+3Ms9XRCOSZ5ULVFCwbFQwjLrg8phlB/Qw21kzGmbqidCtwfDLKsDJ34Y6tekjb84j/GQ3w9XPDQsRx5Q1UxPKgMvBPNmFAZve17o="
  matrix:
    - LLVM_VERSION=3.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq llvm-$LLVM_VERSION

install:
  - pip install coveralls Sphinx
  - cd $HOME
  - git clone git://github.com/llvmpy/llvmpy.git
  - cd llvmpy
  - LLVM_CONFIG_PATH=/usr/bin/llvm-config-$LLVM_VERSION python setup.py install
  - cd ${TRAVIS_BUILD_DIR}

script:
  # run test suite
  - nosetests --with-coverage --cover-package=ctree --cover-min-percentage=90

after_success:

  # publish coverage report
  - coveralls

  # publish documentation
  - "if [[ $(echo $TRAVIS_JOB_NUMBER | cut -d. -f2) -ne 1 ]]; then echo 'Not sub-job #1; skipping doc build.'; exit 0; fi"
  - make -C doc html
  - git fetch origin gh-pages:gh-pages
  - git checkout gh-pages
  - rsync -a doc/_build/html/ ./
  - rm -r doc/_build
  - git config --global user.name 'Ctree Doc Bot'
  - git config --global user.email $GIT_EMAIL
  - git add .
  - git status
  - git commit -m "Updating documentation for commit(s) $TRAVIS_COMMIT_RANGE."
  - git config credential.helper "store --file=.git/credentials"
  - "echo https://${GH_TOKEN}:x-oauth-basic@github.com > .git/credentials"
  - "git push https://github.com/ucb-sejits/ctree.git gh-pages"
