language: python

python:
  - "3.2"
  - "3.3"

env:
  global:
    - secure: "GaaeITRlfMwQ6ybEIdxs3JXVa2NO/Zad6qX/OjLmZcqCupAWdhxmTSpBH9L4TIsFYTNknyUK/+i9dgUDccMlqWudm4NG4DzRWjKyUJYpENT8Gk2MzqcB3Nesc4EUoigMy0rfySXIB3bc25Igu25Hc0o51qTIfE4rIdXdF8RMbsI="

  - LLVM_VERSION=3.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq llvm-$LLVM_VERSION

install:
  - pip install coveralls Sphinx
  - git clone git://github.com/llvmpy/llvmpy.git
  - cd llvmpy
  - LLVM_CONFIG_PATH=/usr/bin/llvm-config-$LLVM_VERSION python setup.py install
  - cd ..

script:
  - nosetests --with-coverage --cover-package=ctree --cover-min-percentage=90

after_success:
  # publish coverage report
  - coveralls

  # publish documentation
  - make -C html
  - git checkout gh-pages
  - cp -r docs/_build/html/* ./
  - rsync -a docs/_build/html .
  - git config --global user.name 'Ctree Doc Bot'
  - git config --global user.email $GIT_EMAIL
  - git add .
  - git commit -m 'Updating documentation for commit $TRAVIS_COMMIT.'
  - git remote add origin_oauth "https://$GIT_NAME:$GH_TOKEN@github.com/ucb-sejits/ctree.git"
  - git push origin gh-pages
