language: python
python:
  - "3.2"
  - "3.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq llvm-3.3

install:
  - pip install coveralls
  - git clone git://github.com/llvmpy/llvmpy.git
  - LLVM_CONFIG_PATH=/usr/bin/llvm-config-3.3 python llvmpy/setup.py install

# command to run tests
script:
  - nosetests --with-coverage --cover-package=ctree

after_success:
  coveralls
