language: python
python:
  - "3.2"
  - "3.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq llvm-3.3

env:
  global:

install:
  - "wget http://llvm.org/releases/3.3/llvm-3.3.src.tar.gz"
  - "tar zxvf llvm-3.3.src.tar.gz"
  - "mkdir llvm-build"
  - "cd llvm-build"
  - "../llvm-3.3.src/configure --enable-optimized --prefix=/opt"
  - "REQUIRES_RTTI=1 make"
  - "git clone git://github.com/llvmpy/llvmpy.git"
  - "cd llvmpy"
  - "LLVM_CONFIG_PATH=/opt/llvm-config python setup.py install"

# command to run tests
script: nosetests
