language: python

python:
  - "3.2"
  - "3.3"

env:
  global:
    # encrypted OAuth token so Travis can commit docs back to Github
    - secure: "GpFIwX6B6SEDBtFjYEGt8Uoa2m2Ho1Y15Q6b7vnRdSVzDx0DKvLlmXKmtEzayu84n0VbonaPepUODdNIaiqwpqIW+S26+ntJsNP3BLWfEZS77tzEdDIpaLXNQaXJCh+KYWe+fHxTreDPZhTKGWmcuwmPvKTSyrPuT/puD7UzkPw="
  matrix:
    - LLVM_VERSION=3.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq llvm-$LLVM_VERSION

install:
  - pip install coveralls Sphinx
  - git clone git://github.com/llvmpy/llvmpy.git
  - cd llvmpy
  - LLVM_CONFIG_PATH=/usr/bin/llvm-config-$LLVM_VERSION python setup.py install
  - cd ..

script:
  # run test suite
  - nosetests --with-coverage --cover-package=ctree --cover-min-percentage=90


after_success:

  # publish coverage report
  - coveralls

  # publish documentation
  - make -C doc html
  - git fetch origin gh-pages
  - git checkout gh-pages
  - rsync -a doc/_build/html/ ./
  - rm -r doc/_build
  - git config --global user.name 'Ctree Doc Bot'
  - git config --global user.email $GIT_EMAIL
  - git add .
  - git status
  - git commit -m 'Updating documentation for commit $TRAVIS_COMMIT.'
  - git push https://$GIT_NAME:$GH_TOKEN@github.com/ucb-sejits/ctree.git gh-pages:gh-pages
