language: python

python:
  - "3.2"
  - "3.3"

env:
  global:
    # encrypted OAuth token so Travis can commit docs back to Github
    - secure: "hT/arLbW8Yi6TFcIJhwU2GQzQpMSgCc0gJePzqtvHoqw6sPOlPCzNK1A7WLrYNn4Yf+byYqOppBi+l1+d5Z5DNVuV4y6SDrP9E6HMaAr3kIAvZNNXjr6qW+I1C2Iswm9oYWZBjm0Mn8fVAGXztSHlCn7npgA5PNN0pKPWOHdRSw="
  matrix:
    - LLVM_VERSION=3.3

before_install:
  #- sudo apt-get update -qq
  #- sudo apt-get install -qq llvm-$LLVM_VERSION

install:
  #- pip install coveralls Sphinx
  #- git clone git://github.com/llvmpy/llvmpy.git
  #- cd llvmpy
  #- LLVM_CONFIG_PATH=/usr/bin/llvm-config-$LLVM_VERSION python setup.py install
  #- cd ..

script:
  # run test suite
  #- nosetests --with-coverage --cover-package=ctree --cover-min-percentage=90
  - echo hi

after_success:

  # publish coverage report
  #- coveralls

  # publish documentation
  - make -C doc html
  - set -ex
  - git fetch origin gh-pages:gh-pages
  - git checkout gh-pages
  - rsync -a doc/_build/html/ ./
  - rm -r doc/_build
  - git config --global user.name 'Ctree Doc Bot'
  - git config --global user.email $GIT_EMAIL
  - git add .
  - git status
  - git remote add oa https://$GIT_NAME:$GH_TOKEN@github.com/ucb-sejits/ctree.git
  - git commit -m "Updating documentation for commit $TRAVIS_COMMIT."
  - "if [[ $(echo $TRAVIS_JOB_NUMBER | cut -d. -f2) -eq 1 ]]; then git push -q oa gh-pages 2>&1 >/dev/null; else echo 'Not first sub-job; skipping push.'; fi 2>&1 >/dev/null"
