language: python
python:
  - "3.2"
  - "3.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq llvm-3.3

env:
  global:
    - LLVM_CONFIG_PATH=/usr/bin/llvm-config-3.3

install:
  - "pip install llvmpy"

# command to run tests
script: nosetests
