language: python

python:
  - "3.2"
  - "3.3"

env:
  global:
    # encrypted OAuth token so Travis can commit docs back to Github
    - secure: "Fgsce4FcT6AZeRMLeZcyKh4HbGI1xrZcxd5s03kAMATHIr8+6S6VVa8MhRgdtDQ7AhIcmpBgXThe2ODArtsGlbuQnkMMRoCOY7xq3j7nchR+xjCQkkWIm2Cji6bklGNi4a51JzvpB+Nu1cyrGYE1zQ3+knM9bMFSTu2DcFIl6F4="
  matrix:
    - LLVM_VERSION=3.3


before_install:

  - sudo apt-get update -qq
  - sudo apt-get install -qq llvm-$LLVM_VERSION


install:

  # coverage and doc generator
  - pip install nose coveralls Sphinx

  # install llvmpy
  - git clone git://github.com/llvmpy/llvmpy.git ${HOME}/llvmpy
  - cd ${HOME}/llvmpy
  - LLVM_CONFIG_PATH=/usr/bin/llvm-config-$LLVM_VERSION python setup.py install

  # install ctree via setup.py
  - cd ${TRAVIS_BUILD_DIR}
  - python setup.py install

script:

  # run test suite from home directory to verify installation
  - cd ${HOME}
  - nosetests --where=${TRAVIS_BUILD_DIR}/test

  # run test suite again from build dir to get coverage info
  - cd ${TRAVIS_BUILD_DIR}
  - nosetests --with-coverage --cover-package=ctree --cover-min-percentage=90


after_success:

  # return early if not building ucb-sejits/ctree
  - "if [[ \"x${TRAVIS_REPO_SLUG}\" != 'xucb-sejits/ctree' ]]; then echo 'skipping coveralls/sphinx for non ucb-sejits/ctree builds.'; exit 0; fi"

  # return early if not the first build in the job
  - "if [[ $(echo ${TRAVIS_JOB_NUMBER} | cut -d. -f2) -ne 1 ]]; then echo 'Not sub-job #1; skipping doc build.'; exit 0; fi"

  # publish coverage report
  - coveralls

  # publish documentation
  - make -C doc html

  - git config --global user.name 'Ctree Doc Bot'
  - git config --global user.email 'mbdriscoll-ctreeoauth@gmail.com'
  - git config credential.helper "store --file=.git/credentials"
  - "echo https://${GH_TOKEN}:x-oauth-basic@github.com > .git/credentials"

  - cd ${HOME}
  - git clone "https://github.com/ucb-sejits/ctree-docs.git"
  - cd ctree-docs
  - git fetch origin gh-pages
  - git checkout gh-pages
  - rsync -a ${TRAVIS_BUILD_DIR}/doc/_build/html/ ./
  - rm -r doc/_build
  - git add .
  - git status
  - git commit -m "Updating documentation for commit(s) $TRAVIS_COMMIT_RANGE."
  - git push origin gh-pages
