language: python

python:
  - "3.2"
  - "3.3"

env:
  global:
    # encrypted OAuth token so Travis can commit docs back to Github
    - secure: "lMJDFi1WZMAproIpCIJwjB9ahwRmV5pjMx8Cb7nE/CHRcrHE0tFlU22OWH7D9Qbj2cXz7xmOg3QUJpVqegY2yZxvVx14Eb9ZoWbGs31FrnNY1IpmIXV7cFRnG4IaVnFh41rkDpDstw97OHnnVRdiRivYeqKSNatc5ceGxDUH7qU="
  matrix:
    - LLVM_VERSION=3.3


before_install:

  - sudo apt-get update -qq
  - sudo apt-get install -qq llvm-$LLVM_VERSION


install:

  # coverage and doc generator
  - pip install coveralls Sphinx

  # install llvmpy
  - git clone git://github.com/llvmpy/llvmpy.git ${HOME}/llvmpy
  - cd ${HOME}/llvmpy
  - LLVM_CONFIG_PATH=/usr/bin/llvm-config-$LLVM_VERSION python setup.py install
  - cd ${TRAVIS_BUILD_DIR}


script:

  # run test suite
  - nosetests --with-coverage --cover-package=ctree --cover-min-percentage=90


after_success:

  # return early if not building ucb-sejits/ctree
  - "if [[ \"x${TRAVIS_REPO_SLUG}\" != 'xucb-sejits/ctree' ]]; then echo 'skipping coveralls/sphinx for non ucb-sejits/ctree builds.'; exit 0; fi"

  # return early if not the first build in the job
  - "if [[ $(echo ${TRAVIS_JOB_NUMBER} | cut -d. -f2) -ne 1 ]]; then echo 'Not sub-job #1; skipping doc build.'; exit 0; fi"

  # publish coverage report
  - coveralls

  # publish documentation
  - "PYTHONPATH=${TRAVIS_BUILD_DIR} make -C doc html"
  - "git fetch origin gh-pages:gh-pages"
  - git checkout gh-pages
  - rsync -a doc/_build/html/ ./
  - rm -r doc/_build
  - git add .
  - git status
  = "git config --global user.name 'Ctree Doc Bot'"
  = "git config --global user.email 'mbdriscoll-ctreeoauth@gmail.com'"
  - git commit -m "Updating documentation for commit(s) $TRAVIS_COMMIT_RANGE."
  - git config credential.helper "store --file=.git/credentials"
  - "echo https://${GH_TOKEN}:x-oauth-basic@github.com > .git/credentials"
  - "git push https://github.com/ucb-sejits/ctree.git gh-pages"
